import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import About from "@/components/main/about";
import Navigation from "@/components/nav";
import Header from "@/components/Header";
import LightRays from "@/components/lightRays";
import SwipeNavigator from "@/components/SwipeNavigatorAnimated";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212]`}
      >
        <LightRays
          raysOrigin="top-center"
          raysColor="#00ffff"
          raysSpeed={1.5}
          lightSpread={0.8}
          rayLength={1.2}
          followMouse={true}
          mouseInfluence={0.1}
          noiseAmount={0.1}
          distortion={0.05}
          className="custom-rays"
        />

        <Navigation />

        {/* Swipe navigation across main routes (mobile/tablet). Order determines next/previous. */}
        <SwipeNavigator
          routes={["/", "/projects", "/game", "/qualification", "/socials"]}
        />

        <div className="min-h-screen w-screen flex flex-col items-center justify-between overflow-x-hidden pt-16 md:pt-20 pb-20 md:pb-24 relative z-10">
          <Header />
          <div className="flex-1 flex items-center justify-center w-full max-w-screen-xl mx-auto px-4 md:px-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
